version: "3.8"

services:
  dashboard:
    build:
      context: ./
      dockerfile: src/dashboard/Dockerfile
    restart: always
    environment:
      - "LOGGING_ENABLED=false"
      - "ENABLE_API=false"
      - "ORACLE_DB_FROM_ENV=false"
      - "SQL_LITE=false"
      - "POSTGRE_DB_FROM_ENV=true"
      - "POSTGRE_USER=${POSTGRE_USER}"
      - "POSTGRE_PASSWORD=${POSTGRE_PASSWORD}"
      - "POSTGRE_DB=${POSTGRE_DB}"
      - "POSTGRE_HOST=${POSTGRE_HOST}"
      - "POSTGRE_PORT=${POSTGRE_PORT}"

    ports:
      - "${DASHBOARD_PORT}:8501"

  api:
    build:
      context: ./
      dockerfile: src/api/Dockerfile
    restart: always

    environment:
      - "LOGGING_ENABLED=false"
      - "ENABLE_API=false"
      - "ORACLE_DB_FROM_ENV=false"
      - "SQL_LITE=false"
      - "POSTGRE_DB_FROM_ENV=true"
      - "POSTGRE_USER=${POSTGRE_USER}"
      - "POSTGRE_PASSWORD=${POSTGRE_PASSWORD}"
      - "POSTGRE_DB=${POSTGRE_DB}"
      - "POSTGRE_HOST=${POSTGRE_HOST}"
      - "POSTGRE_PORT=${POSTGRE_PORT}"
    ports:
      - "${API_PORT}:8180"
