version: "3.8"

services:
  dashboard:
    build:
      context: ./
      dockerfile: src/dashboard/Dockerfile
    restart: always
    environment:
      - "ORACLE_DSN=${ORACLE_DSN}"
      - "ORACLE_USER=${ORACLE_USER}"
      - "ORACLE_PASSWORD=${ORACLE_PASSWORD}"
    ports:
      - "${DASHBOARD_PORT}:8501"

  api:
    build:
      context: ./
      dockerfile: src/api/Dockerfile
    restart: always

    environment:
      - "ORACLE_DSN=${ORACLE_DSN}"
      - "ORACLE_USER=${ORACLE_USER}"
      - "ORACLE_PASSWORD=${ORACLE_PASSWORD}"

    ports:
      - "${API_PORT}:8180"
