version: "3.8"

services:
  dashboard:
    build:
      context: ./
      dockerfile: src/dashboard/Dockerfile
    restart: always
    ports:
      - "${DASHBOARD_PORT}:8501"

  api:
    build:
      context: ./
      dockerfile: src/api/Dockerfile
    restart: always
#    environment:
#      - DATABASE_URL=postgresql://postgres:password@db:5432/mydatabase
    ports:
      - "${API_PORT}:8180"
