version: "3.8"

services:
  dashboard:
    build:
      context: ./
      dockerfile: src/dashboard/Dockerfile
    restart: always

#  api:
#    build:
#      context: ./
#      dockerfile: src/api/Dockerfile
#    restart: always
#    environment:
#      - DATABASE_URL=postgresql://postgres:password@db:5432/mydatabase