# AUTOGENERATED FILE - DO NOT EDIT
# Generated by generators/generate_model_imports.py
#
# This file contains static imports for all Model subclasses.
# It is generated at Docker build time to replace dynamic imports.

import importlib
import logging

logger = logging.getLogger(__name__)


def import_generated_models() -> None:
    """
    Import all modules that contain Model subclasses.
    
    This function is called by import_models() to statically import
    all model modules, providing better performance and determinism
    than dynamic imports at runtime.
    """
    # Importing 4 model module(s)
    try:
        importlib.import_module("src.database.models.empresa")
    except ImportError as e:
        logger.error(f"Failed to import src.database.models.empresa: {e}")
    try:
        importlib.import_module("src.database.models.equipamento")
    except ImportError as e:
        logger.error(f"Failed to import src.database.models.equipamento: {e}")
    try:
        importlib.import_module("src.database.models.manutencao_equipamento")
    except ImportError as e:
        logger.error(f"Failed to import src.database.models.manutencao_equipamento: {e}")
    try:
        importlib.import_module("src.database.models.sensor")
    except ImportError as e:
        logger.error(f"Failed to import src.database.models.sensor: {e}")
