# AUTOGENERATED FILE - DO NOT EDIT
# Generated by generators/generate_tool_imports.py
#
# This file contains static imports for all BaseTool subclasses.
# It is generated to replace dynamic imports.

import importlib
import logging

logger = logging.getLogger(__name__)


def import_generated_tools() -> None:
    """
    Import all modules that contain BaseTool subclasses.
    
    This function is called by import_tools() to statically import
    all tool modules, providing better performance and determinism
    than dynamic imports at runtime.
    """
    # Importing 10 tool module(s)
    try:
        importlib.import_module("src.large_language_model.tools.agendar_manutencao_tool")
    except ImportError as e:
        logger.error(f"Failed to import src.large_language_model.tools.agendar_manutencao_tool: {e}")
    try:
        importlib.import_module("src.large_language_model.tools.analisar_dados_sensor_tool")
    except ImportError as e:
        logger.error(f"Failed to import src.large_language_model.tools.analisar_dados_sensor_tool: {e}")
    try:
        importlib.import_module("src.large_language_model.tools.count_equipamentos_tool")
    except ImportError as e:
        logger.error(f"Failed to import src.large_language_model.tools.count_equipamentos_tool: {e}")
    try:
        importlib.import_module("src.large_language_model.tools.datetime_tool")
    except ImportError as e:
        logger.error(f"Failed to import src.large_language_model.tools.datetime_tool: {e}")
    try:
        importlib.import_module("src.large_language_model.tools.enviar_notificacao_tool")
    except ImportError as e:
        logger.error(f"Failed to import src.large_language_model.tools.enviar_notificacao_tool: {e}")
    try:
        importlib.import_module("src.large_language_model.tools.gerar_grafico_leituras_tool")
    except ImportError as e:
        logger.error(f"Failed to import src.large_language_model.tools.gerar_grafico_leituras_tool: {e}")
    try:
        importlib.import_module("src.large_language_model.tools.listar_equipamentos_tool")
    except ImportError as e:
        logger.error(f"Failed to import src.large_language_model.tools.listar_equipamentos_tool: {e}")
    try:
        importlib.import_module("src.large_language_model.tools.listar_sensores_tool")
    except ImportError as e:
        logger.error(f"Failed to import src.large_language_model.tools.listar_sensores_tool: {e}")
    try:
        importlib.import_module("src.large_language_model.tools.prever_necessidade_manutencao_tool")
    except ImportError as e:
        logger.error(f"Failed to import src.large_language_model.tools.prever_necessidade_manutencao_tool: {e}")
    try:
        importlib.import_module("src.large_language_model.tools.prever_por_valores_tool")
    except ImportError as e:
        logger.error(f"Failed to import src.large_language_model.tools.prever_por_valores_tool: {e}")
